export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: '01背包问题',
        author: 'Canvas',
        dateStr: 'May 12nd，2018',
        desc: '01背包问题',
        link: '/zh-cn/blog/0-1-backpack.html',
      },
      {
        title: 'macOS开启任何来源',
        author: 'Canvas',
        dateStr: 'May 2nd，2018',
        desc: 'macOS开启任何来源',
        link: '/zh-cn/blog/Allow-apps-downloaded-from-anywhere-in-macOS.html',
      },
      {
        title: 'CAS 5.3.4 安装部署',
        author: 'Canvas',
        dateStr: 'April 25th，2018',
        desc: 'CAS 5.3.4 安装部署',
        link: '/zh-cn/blog/CAS-5-3-4-install-and-deploy.html',
      },
      {
        title: 'CentOS 安装部署 openLDAP',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'CentOS 安装部署 openLDAP',
        link: '/zh-cn/blog/CentOS-install-openLDAP.html',
      },
      {
        title: 'TestLink 安装部署',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'TestLink 安装部署',
        link: '/zh-cn/blog/TestLink-install-and-deploy.md.html.html',
      },
      {
        title: 'TestLink 整合 LDAP 和 CAS 单点登录',
        author: 'author6',
        dateStr: 'April 22nd，2018',
        desc: 'TestLink 整合 LDAP 和 CAS 单点登录',
        link: '/zh-cn/blog/TestLink-integrate-with-ldap-and-CAS.html',
      },
      {
        title: 'SonarQube 安装部署',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'SonarQube 安装部署',
        link: '/zh-cn/blog/SonarQube-install-and-deploy.html',
      },
      {
        title: 'SonarQube 整合 LDAP 和 CAS 单点登录',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'SonarQube 整合 LDAP 和 CAS 单点登录',
        link: '/zh-cn/blog/SonarQube-integrate-with-ldap-and-CAS.html',
      },
      {
        title: 'CentOS 搭建 ShadowSocks 访问墙外的世界',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'CentOS 搭建 ShadowSocks 访问墙外的世界',
        link: '/zh-cn/blog/shadowsocks-libev.html',
      },
      {
        title: 'CentOS 安装部署 MantisBT',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'CentOS 安装部署 MantisBT',
        link: '/zh-cn/blog/MantisBT-install-and-deploy.html',
      },
      {
        title: 'MantisBT 整合 LDAP 和 CAS 单点登录',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'MantisBT 整合 LDAP 和 CAS 单点登录',
        link: '/zh-cn/blog/MantisBT-integrate-with-ldap-and-CAS.html',
      },
      {
        title: 'CentOS 安装部署 Jenkins',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'CentOS 安装部署 Jenkins',
        link: '/zh-cn/blog/Jenkins-configure-and-deploy.md.html',
      },
      {
        title: 'Jenkins 整合 LDAP 和 CAS 单点登录',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'Jenkins 整合 LDAP 和 CAS 单点登录',
        link: '/zh-cn/blog/Jenkins-integrate-with-ldap-and-CAS.html',
      },
      {
        title: '笔记本安装黑苹果教程',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: '笔记本安装黑苹果教程',
        link: '/zh-cn/blog/Install-macOS-on-laptop.html',
      },
      {
        title: 'CentOS 安装部署 Gerrit',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'CentOS 安装部署 Gerrit',
        link: '/zh-cn/blog/Gerrit-install-and-deploy.html',
      },
      {
        title: 'Gerrit 整合 LDAP 和 CAS 单点登录',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'Gerrit 整合 LDAP 和 CAS 单点登录',
        link: '/zh-cn/blog/Gerrit-integrate-with-ldap-and-CAS.html',
      },
      {
        title: 'iTerm2 + ohmyzsh + powerlevel9k + tmux 打造专属个性化终端',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'iTerm2 + ohmyzsh + powerlevel9k + tmux 打造专属个性化终端',
        link: '/zh-cn/blog/Custom-terminal-on-your-mac.html',
      },
    ],
  },
  'zh-cn': {
    barText: '博客',
    postsTitle: '所有文章',
    list: [
      {
        title: '01背包问题',
        author: 'Canvas',
        dateStr: 'May 12nd，2018',
        desc: '01背包问题',
        link: '/zh-cn/blog/0-1-backpack.html',
      },
      {
        title: 'macOS开启任何来源',
        author: 'Canvas',
        dateStr: 'May 2nd，2018',
        desc: 'macOS开启任何来源',
        link: '/zh-cn/blog/Allow-apps-downloaded-from-anywhere-in-macOS.html',
      },
      {
        title: 'CAS 5.3.4 安装部署',
        author: 'Canvas',
        dateStr: 'April 25th，2018',
        desc: 'CAS 5.3.4 安装部署',
        link: '/zh-cn/blog/CAS-5-3-4-install-and-deploy.html',
      },
      {
        title: 'CentOS 安装部署 openLDAP',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'CentOS 安装部署 openLDAP',
        link: '/zh-cn/blog/CentOS-install-openLDAP.html',
      },
      {
        title: 'TestLink 安装部署',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'TestLink 安装部署',
        link: '/zh-cn/blog/TestLink-install-and-deploy.md.html.html',
      },
      {
        title: 'TestLink 整合 LDAP 和 CAS 单点登录',
        author: 'author6',
        dateStr: 'April 22nd，2018',
        desc: 'TestLink 整合 LDAP 和 CAS 单点登录',
        link: '/zh-cn/blog/TestLink-integrate-with-ldap-and-CAS.html',
      },
      {
        title: 'SonarQube 安装部署',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'SonarQube 安装部署',
        link: '/zh-cn/blog/SonarQube-install-and-deploy.html',
      },
      {
        title: 'SonarQube 整合 LDAP 和 CAS 单点登录',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'SonarQube 整合 LDAP 和 CAS 单点登录',
        link: '/zh-cn/blog/SonarQube-integrate-with-ldap-and-CAS.html',
      },
      {
        title: 'CentOS 搭建 ShadowSocks 访问墙外的世界',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'CentOS 搭建 ShadowSocks 访问墙外的世界',
        link: '/zh-cn/blog/shadowsocks-libev.html',
      },
      {
        title: 'CentOS 安装部署 MantisBT',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'CentOS 安装部署 MantisBT',
        link: '/zh-cn/blog/MantisBT-install-and-deploy.html',
      },
      {
        title: 'MantisBT 整合 LDAP 和 CAS 单点登录',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'MantisBT 整合 LDAP 和 CAS 单点登录',
        link: '/zh-cn/blog/MantisBT-integrate-with-ldap-and-CAS.html',
      },
      {
        title: 'CentOS 安装部署 Jenkins',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'CentOS 安装部署 Jenkins',
        link: '/zh-cn/blog/Jenkins-configure-and-deploy.md.html',
      },
      {
        title: 'Jenkins 整合 LDAP 和 CAS 单点登录',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'Jenkins 整合 LDAP 和 CAS 单点登录',
        link: '/zh-cn/blog/Jenkins-integrate-with-ldap-and-CAS.html',
      },
      {
        title: '笔记本安装黑苹果教程',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: '笔记本安装黑苹果教程',
        link: '/zh-cn/blog/Install-macOS-on-laptop.html',
      },
      {
        title: 'CentOS 安装部署 Gerrit',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'CentOS 安装部署 Gerrit',
        link: '/zh-cn/blog/Gerrit-install-and-deploy.html',
      },
      {
        title: 'Gerrit 整合 LDAP 和 CAS 单点登录',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'Gerrit 整合 LDAP 和 CAS 单点登录',
        link: '/zh-cn/blog/Gerrit-integrate-with-ldap-and-CAS.html',
      },
      {
        title: 'iTerm2 + ohmyzsh + powerlevel9k + tmux 打造专属个性化终端',
        author: 'Canvas',
        dateStr: 'April 22nd，2018',
        desc: 'iTerm2 + ohmyzsh + powerlevel9k + tmux 打造专属个性化终端',
        link: '/zh-cn/blog/Custom-terminal-on-your-mac.html',
      },
    ],
  },
};
